\include "english.ly"
\header{
  title = "sheets_x.ly"
  tagline = \markup \center-column {"Tab generated by the Holdsworth library" "Command Line: fing --statistics --extended --output=sheets_x --test=sheets"}
}
frag = {
\override Glissando #'gap = #0.01
\override Glissando #'style = #'zigzag
a'16-3^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-10-3;1-7-1;1-9-2;" } }
b'-1^\markup { \center-column {  "s" } }
csharp''-2
csharp''-2
b'-1^\markup { \center-column {  "s" } }
a'-3
a'-3\glissando 
b'-3^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-12-3;1-9-1;1-12-3;1-13-4;1-11-2;1-10-1;2-13-4;2-11-2;""*" } }
csharp''-1^\markup { \center-column {  "s" } }
csharp''-1^\markup { \center-column {  "s" } }
e''-3
f''-4
e''-3
csharp''-1^\markup { \center-column {  "s" } }
b'-3
dsharp''-2
d''-1
c''-4
b'-3
asharp'-2
c''-4
dsharp''-2
e''-3
b'-4^\markup { \center-column {  "Q" } }
asharp'-2\glissando 
csharp''-2^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-14-2;1-13-1;2-15-3;2-13-1;3-16-4;3-14-2;3-13-1;4-16-4;4-14-2;4-13-1;3-12-1;2-12-1;2-16-4;""+c" } }
f''-1
csharp''-2
d''-3
c''-1
b'-4
c''-1
a'-2
gsharp'-1
fsharp'-4
e'-2
dsharp'-1
e'-2
gsharp'-1
dsharp'-2^\markup { \center-column {  "Q" } }
fsharp'-4
e'-2
dsharp'-1
e'-2
fsharp'-4
g'-1^\markup { \center-column {  "s" } }
a'-2
b'-4
b'-4
d''-3
b'-1^\markup { \center-column {  "s" } }
c''-1^\markup { \center-column {  "A" } }
d''-3
dsharp''-4
d''-3
c''-1\glissando 
asharp'-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-11-1;2-13-2;2-15-4;1-11-1;""s*" } }
c''-2
d''-4
dsharp''-1^\markup { \center-column {  "s" } }
gsharp''-3^\markup { \center-column {  \fret-diagram #"s:1;f:1;1-16-3;1-13-1;2-16-3;2-13-1;3-15-2;3-17-4;2-15-2;1-15-2;1-17-4;2-17-4;3-14-1;4-17-4;4-15-2;""*" } }
f''-1^\markup { \center-column {  "s" } }
dsharp''-3
dsharp''-3
f''-1^\markup { \center-column {  "s" } }
dsharp''-3
dsharp''-3
c''-1^\markup { \center-column {  "s" } }
asharp'-2
c''-4
d''-2
f''-1^\markup { \center-column {  "s" } }
g''-2
a''-4
c''-1^\markup { \center-column {  "s" } }
d''-2
e''-4
a'-1
c''-4
asharp'-2
a'-1
g'-4
asharp'-2
a'-1
g'-4
f'-2\glissando 
e'-2\glissando ^\markup { \center-column {  "*" } }
f'-2^\markup { \center-column {  \fret-diagram #"s:1;f:1;4-15-2;4-17-4;""*" } }
g'-4
f'-2
 r8  r4 }
fragt = {
\override Glissando #'gap = #0.01
\override Glissando #'style = #'zigzag
a'16\2
b'\1
csharp''\1
csharp''\1
b'\1
a'\2
a'\2\glissando 
b'\2
csharp''\1
csharp''\1
e''\1
f''\1
e''\1
csharp''\1
b'\2
dsharp''\1
d''\1
c''\2
b'\2
asharp'\2
c''\2
dsharp''\1
e''\1
b'\2
asharp'\2\glissando 
csharp''\2
f''\1
csharp''\2
d''\2
c''\2
b'\3
c''\2
a'\3
gsharp'\3
fsharp'\4
e'\4
dsharp'\4
e'\4
gsharp'\3
dsharp'\4
fsharp'\4
e'\4
dsharp'\4
e'\4
fsharp'\4
g'\3
a'\3
b'\3
b'\3
d''\2
b'\2
c''\2
d''\2
dsharp''\2
d''\2
c''\2\glissando 
asharp'\2
c''\2
d''\2
dsharp''\1
gsharp''\1
f''\1
dsharp''\2
dsharp''\2
f''\1
dsharp''\2
dsharp''\2
c''\2
asharp'\3
c''\3
d''\2
f''\1
g''\1
a''\1
c''\2
d''\2
e''\2
a'\3
c''\3
asharp'\3
a'\3
g'\4
asharp'\3
a'\3
g'\4
f'\4\glissando 
e'\4\glissando 
f'\4
g'\4
f'\4
 r8  r4 }
\new StaffGroup << \new Staff { \clef "G_8" \key c \major  \frag } \new TabStaff { \fragt } >> 
