\include "english.ly"
\header{
  title = "unmerry_b2b.ly"
  tagline = \markup \center-column {"Tab generated by the Holdsworth library" "Command Line: fing --statistics --back-to-back --output=unmerry_b2b"}
}
frag = {
\override Glissando #'gap = #0.01
\override Glissando #'style = #'zigzag
d''16-4^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-15-4;1-12-1;1-15-4;1-13-2;2-14-3;2-12-1;3-14-3;""-c" } }
e''-1
g''-4
f''-2
e''-1
csharp''-3
d''-4
csharp''-3
b'-1
a'-3
fsharp'-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-7-1;3-9-3;2-8-2;2-10-4;3-7-1;4-9-3;4-7-1;5-10-4;5-7-1;6-10-4;6-7-1;""*" } }
e'-3
fsharp'-1
g'-2
a'-4
g'-2
fsharp'-1
e'-3
e'-3
d'-1
e'-3
d'-1
b-3
a-1
g-4
e-1
d-4
b,-1\glissando 
csharp-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;6-9-1;6-10-2;3-9-1;3-10-2;3-12-4;1-9-1;1-10-2;1-12-4;5-12-4;5-10-2;""*" } }
d-2
e'-1
f'-2
g'-4
csharp''-1
d''-2
e''-4
d''-2
csharp''-1
g'-4
f'-2
e'-1
a-4
g-2
f-4^\markup { \center-column {  \fret-diagram #"s:1;f:1;6-13-4;5-10-1;5-12-3;4-12-3;""*" } }
g-1
a-3
d'-3^\markup { \center-column {  "L" } }
d'-3
g,-2^\markup { \center-column {  \fret-diagram #"s:1;f:1;6-3-2;5-2-1;4-3-2;3-2-1;""=+c" } }
b,-1
f-2
a-1\glissando 
b-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;3-4-1;6-5-2;5-4-1;4-5-2;""*" } }
a,-2
csharp-1
g-2
b-1\glissando 
csharp'-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;3-6-1;5-9-4;4-7-2;3-7-2;3-9-4;""*" } }
fsharp-4
a-2
a-2
d'-2^\markup { \center-column {  "L" } }
e'-4
d'-3^\markup { \center-column {  \fret-diagram #"s:1;f:1;3-7-3;3-6-2;2-5-1;2-7-3;2-8-4;1-5-1;""*c*" } }
csharp'-2
d'-3
csharp'-2
d'-3
e'-1
fsharp'-3
g'-4
a'-1
a'-1
g'-4
fsharp'-3
g'-4
a'-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;1-5-1;1-7-3;2-8-4;""*c" } }
b'-3
b'-3
a'-1
g'-4
a'-1\glissando 
b'-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;1-7-1;1-9-3;2-10-4;1-10-4;""+c" } }
csharp''-3
csharp''-3
b'-1
a'-4
b'-1
csharp''-3
d''-4
e''-1^\markup { \center-column {  \fret-diagram #"s:1;f:1;2-17-1;2-20-4;1-17-1;1-19-3;""*!" } }
g''-4
a''-1
b''-3
a''-1
a''-1
}
fragt = {
\override Glissando #'gap = #0.01
\override Glissando #'style = #'zigzag
d''16\2
e''\1
g''\1
f''\1
e''\1
csharp''\2
d''\2
csharp''\2
b'\2
a'\3
fsharp'\2
e'\3
fsharp'\2
g'\2
a'\2
g'\2
fsharp'\2
e'\3
e'\3
d'\3
e'\3
d'\3
b\4
a\4
g\5
e\5
d\6
b,\6\glissando 
csharp\6
d\6
e'\3
f'\3
g'\3
csharp''\1
d''\1
e''\1
d''\1
csharp''\1
g'\3
f'\3
e'\3
a\5
g\5
f\6
g\5
a\5
d'\4
d'\4
g,\6
b,\5
f\4
a\3\glissando 
b\3
a,\6
csharp\5
g\4
b\3\glissando 
csharp'\3
fsharp\5
a\4
a\4
d'\3
e'\3
d'\3
csharp'\3
d'\3
csharp'\3
d'\3
e'\2
fsharp'\2
g'\2
a'\1
a'\1
g'\2
fsharp'\2
g'\2
a'\1
b'\1
b'\1
a'\1
g'\2
a'\1\glissando 
b'\1
csharp''\1
csharp''\1
b'\1
a'\2
b'\1
csharp''\1
d''\1
e''\2
g''\2
a''\1
b''\1
a''\1
a''\1
}
\new StaffGroup << \new Staff { \clef "G_8" \key c \major  \frag } \new TabStaff { \fragt } >> 
